# Generated by Django 4.2 on 2024-11-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(verbose_name='1403/08/16'),
        ),
    ]
