# Generated by Django 4.2 on 2024-11-06 18:53

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=django_jalali.db.models.jDateField(auto_now=True),
        ),
    ]
