# Generated by Django 4.2 on 2024-11-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=48)),
                ('is_active', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, default=' ', max_length=254)),
            ],
        ),
    ]
